name: Verificação Básica

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1'
    
    - name: Instalar dependências
      run: |
        pip install requests beautifulsoup4 pdfplumber
        
    - name: Executar script principal
      run: python WebScraping.py