name: CI com Semantic Release

on:
  push:
    branches:
      - main
      
jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  

    - name: Instalar dependências
      run: |
        pip install requests beautifulsoup4 pdfplumber


    - name: Executar script principal
      run: python WebScraping.py
