name: Automated Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Necessário para o changelog

    - name: Generate Changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.3
      with:
        token: ${{ github.token }}
        output: CHANGELOG.md

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        body_path: CHANGELOG.md
        files: |
          WebScraping.py
          script.sql
          README.md